[package]
name = "redis-evaljs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "redisjs"

[dependencies]
num_cpus = "1.17.0"
rquickjs = { version = "0.9.0", features = ["parallel"] }
redis-module = "2.0.7"
once_cell = "1.19"
