MODULE_PATH="${MODULE_PATH:-$(pwd)/target/release/libredisjs.so}"

setup_file() {
    local port=$((16379 + RANDOM % 10000))
    valkey-server --port "$port" --loadmodule "$MODULE_PATH" \
        --logfile /tmp/evaljs-bats-server.log --daemonize no &
    echo $! > /tmp/evaljs-bats-server.pid
    echo "$port" > /tmp/evaljs-bats-server.port

    for _ in $(seq 1 50); do
        if valkey-cli -p "$port" ping >/dev/null 2>&1; then
            return
        fi
        sleep 0.1
    done

    echo "valkey-server failed to start on port $port" >&2
    return 1
}

teardown_file() {
    local pid
    pid=$(cat /tmp/evaljs-bats-server.pid 2>/dev/null)
    if [[ -n "$pid" ]]; then
        kill "$pid" 2>/dev/null || true
        wait "$pid" 2>/dev/null || true
    fi
    rm -f /tmp/evaljs-bats-server.pid /tmp/evaljs-bats-server.port
}

setup() {
    EVALJS_TEST_PORT=$(cat /tmp/evaljs-bats-server.port)
    valkey-cli -p "$EVALJS_TEST_PORT" flushdb
}

@test "simple expression" {
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return 41 + 1" 0
    [ "$status" -eq 0 ]
    [ "$output" = "42" ]
}

@test "output string" {
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return 'hello!'" 0
    [ "$status" -eq 0 ]
    [ "$output" = "hello!" ]
}

@test "output integer" {
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return 42" 0
    [ "$status" -eq 0 ]
    [ "$output" = 42 ]
}

@test "output float" {
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return 3.14" 0
    [ "$status" -eq 0 ]
    [ "$output" = 3.14 ]
}

@test "output null, undefined as null" {
    function t() {
        run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "$@" 0
        [ "$status" -eq 0 ]
        [ "$output" = "" ]
    }

    t "return null"
    t "return undefined"
}

@test "unknown, uninitialized throws exception" {
    function t() {
        run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "$@" 0
        echo "output: '$output'"
        [ "$status" -eq 0 ]
        [ "$output" = "Exception generated by QuickJS" ]
    }

    t "return uninitialized"
    t "return unknown"
}

@test "evaluate function" {
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "const f = (a, b) => a*b; return f(2, 3)" 0
    [ "$status" -eq 0 ]
    [ "$output" = "6" ]
}

@test "evaluate array" {
    want=$(cat <<EOF
1
2
3
EOF
)
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return [3, 2, 1].sort((a, b) => a - b)" 0
    [ "$status" -eq 0 ]
    [ "$output" = "$want" ]
}

@test "argv and keys" {
    want=$(cat <<EOF
key1
key2
arg1
arg2
arg3
EOF
)
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return [KEYS[0], KEYS[1], ARGV[0], ARGV[1], ARGV[2]]" 2 key1 key2 arg1 arg2 arg3
    [ "$status" -eq 0 ]
    [ "$output" = "$want" ]
}

@test "redis.call" {
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return redis.call('SET', 'a', 42)" 0
    [ "$status" -eq 0 ]
    [ "$output" = "OK" ]

    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return redis.call('GET', 'a')" 0
    [ "$status" -eq 0 ]
    [ "$output" = "42" ]
}

@test "distributed lock" {
    # Test acquiring lock
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return redis.call('SET', KEYS[0], ARGV[0], 'NX', 'PX', ARGV[1]) ? 1 : 0;" 1 my_lock abc123 30000
    [ "$status" -eq 0 ]
    [ "$output" = "1" ]

    # Test acquiring the same lock again (should fail)
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return redis.call('SET', KEYS[0], ARGV[0], 'NX', 'PX', ARGV[1]) ? 1 : 0;" 1 my_lock abc123 30000
    [ "$status" -eq 0 ]
    [ "$output" = "0" ]

    # Test unlocking with correct token
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return redis.call('GET', KEYS[0]) === ARGV[0] ? redis.call('DEL', KEYS[0]) : 0;" 1 my_lock abc123
    [ "$status" -eq 0 ]
    [ "$output" = "1" ]

    # Test unlocking again (should fail since lock is already released)
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return redis.call('GET', KEYS[0]) === ARGV[0] ? redis.call('DEL', KEYS[0]) : 0;" 1 my_lock abc123
    [ "$status" -eq 0 ]
    [ "$output" = "0" ]

    # Test unlocking with wrong token
    valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return redis.call('SET', KEYS[0], ARGV[0], 'NX', 'PX', ARGV[1]) ? 1 : 0;" 1 my_lock abc123 30000
    run valkey-cli -p "$EVALJS_TEST_PORT" EVALJS "return redis.call('GET', KEYS[0]) === ARGV[0] ? redis.call('DEL', KEYS[0]) : 0;" 1 my_lock wrong_token
    [ "$status" -eq 0 ]
    [ "$output" = "0" ]
}